export const endpoints = {
  auth: {
    register: '/api/auth/register',
    login: '/api/auth/login',
    me: '/api/auth/me',
    logout: '/api/auth/logout',
  },
  manifests: {
    kpis: '/api/manifests/kpis',
    trend: '/api/manifests/trend',
    trends: '/api/manifests/trends',
    map: '/api/manifests/map',
    ranking: '/api/manifests/ranking',
    routeRanking: '/api/manifests/ranking-routes',
    companyRanking: '/api/manifests/ranking-companies',
    distribution: '/api/manifests/distribution',
    top20: '/api/manifests/top20',
    summary: '/api/manifests/summary',
  },
  telemetry: {
    kpis: '/api/telemetry/kpis',
    events: '/api/telemetry/events',
    speed: '/api/telemetry/speed',
    speeds: '/api/telemetry/speeds',
    alerts: '/api/telemetry/alerts',
    corridor: '/api/telemetry/corridor',
    securityEvents: '/api/telemetry/security-events',
    report: '/api/telemetry/report',
    upload: '/api/telemetry/upload',
  },
  telemetryRoutes: {
    files: '/api/telemetry/routes/files',
    vehicles: '/api/telemetry/routes/vehicles',
    months: '/api/telemetry/routes/months',
    map: '/api/telemetry/routes/map',
    events: '/api/telemetry/routes/events',
  },
  routes: {
    kpis: '/api/routes/kpis',
    corridors: '/api/routes/corridors',
    departments: '/api/routes/departments',
    flow: '/api/routes/flow',
    heatmap: '/api/routes/heatmap',
    history: '/api/routes/history',
    productionMap: '/api/routes/production-map',
    demandMap: '/api/routes/demand-map',
    royaltiesMap: '/api/routes/royalties-map',
  },
  companies: {
    kpis: '/api/companies/kpis',
    list: '/api/companies/list',
    ranking: '/api/companies/ranking',
    detail: (companyId: string) => `/api/companies/${companyId}`,
  },
  companyPortal: {
    files: '/api/company-files',
    upload: '/api/company-files/upload',
    summary: '/api/company-files/summary',
    detail: (fileId: string) => `/api/company-files/${fileId}`,
    insights: (fileId: string) => `/api/company-files/${fileId}/insights`,
    reports: '/api/company-files/reports',
  },
  stats: {
    dashboard: '/api/stats/dashboard',
    health: '/api/stats/health',
    kpis: '/api/stats/kpis',
    trends: '/api/stats/trends',
    summary: '/api/stats/summary',
  },
  export: {
    combined: '/api/export/combined',
  },
} as const;
